name: Deploy Theme
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: TryGhost/action-deploy-theme@v1.4.1
        with:
          theme-name: "codrill-dawn"
          exclude: "gulpfile.js *dist/*"
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}